"""rename_shift_to_shift_template_and_create_shift_shift_user_product_slot_reading_tables

Revision ID: 105ae8649699
Revises: 3ae6e514ca05
Create Date: 2026-03-01 16:10:47.623798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '105ae8649699'
down_revision: Union[str, Sequence[str], None] = '3ae6e514ca05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Rename shift table to shift_template and add order column
    op.rename_table('shift', 'shift_template')
    op.add_column('shift_template', sa.Column('order', sa.Integer(), nullable=True))  # Nullable first
    
    # Create new shift table with new schema
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_template_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('actual_start_datetime', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('actual_end_datetime', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('started_by', sa.Integer(), nullable=False),
    sa.Column('ended_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ended_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_template.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create shift_user table
    op.create_table('shift_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_user_id'), 'shift_user', ['id'], unique=False)
    
    # Create product_slot_reading table
    op.create_table('product_slot_reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('product_slot_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('start_reading', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('end_reading', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('start_reading_image_url', sa.String(), nullable=False),
    sa.Column('end_reading_image_url', sa.String(), nullable=True),
    sa.Column('cost_price_snapshot', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('selling_price_snapshot', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_slot_id'], ['product_slot.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shift.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shift_id', 'product_slot_id', name='_shift_product_slot_uc')
    )
    op.create_index(op.f('ix_product_slot_reading_id'), 'product_slot_reading', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_slot_reading_id'), table_name='product_slot_reading')
    op.drop_table('product_slot_reading')
    op.drop_index(op.f('ix_shift_user_id'), table_name='shift_user')
    op.drop_table('shift_user')
    op.drop_index(op.f('ix_shift_id'), table_name='shift')
    op.drop_table('shift')
    op.drop_column('shift_template', 'order')
    op.rename_table('shift_template', 'shift')
    # ### end Alembic commands ###
