"""add cost_price, selling_price, created_at, created_by, updated_at, updated_by to product

Revision ID: 2cf4a958cc91
Revises: e82ca65e57c3
Create Date: 2026-02-07 23:44:16.881814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2cf4a958cc91'
down_revision: Union[str, Sequence[str], None] = 'e82ca65e57c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cost_price', sa.Numeric(precision=15, scale=6), nullable=False, server_default='0'))
    op.add_column('product', sa.Column('selling_price', sa.Numeric(precision=15, scale=6), nullable=False, server_default='0'))
    op.add_column('product', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('product', sa.Column('updated_by', sa.Integer(), nullable=True))
    # Remove server_default after adding columns (only needed for existing rows)
    op.alter_column('product', 'cost_price', server_default=None)
    op.alter_column('product', 'selling_price', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'updated_by')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'created_by')
    op.drop_column('product', 'created_at')
    op.drop_column('product', 'selling_price')
    op.drop_column('product', 'cost_price')
    # ### end Alembic commands ###
