"""create product table

Revision ID: 3569b373ea14
Revises: 10289ed66493
Create Date: 2026-02-07 23:23:47.863696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '3569b373ea14'
down_revision: Union[str, Sequence[str], None] = '10289ed66493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('starting_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('running_stock', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_template_id'], ['product_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###
