"""increase decimal precision for product stock fields

Revision ID: e82ca65e57c3
Revises: 3569b373ea14
Create Date: 2026-02-07 23:26:51.162554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82ca65e57c3'
down_revision: Union[str, Sequence[str], None] = '3569b373ea14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'starting_stock',
                    type_=sa.Numeric(precision=15, scale=6),
                    existing_type=sa.Numeric(precision=10, scale=2),
                    existing_nullable=False)
    op.alter_column('product', 'running_stock',
                    type_=sa.Numeric(precision=15, scale=6),
                    existing_type=sa.Numeric(precision=10, scale=2),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'running_stock',
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_type=sa.Numeric(precision=15, scale=6),
                    existing_nullable=False)
    op.alter_column('product', 'starting_stock',
                    type_=sa.Numeric(precision=10, scale=2),
                    existing_type=sa.Numeric(precision=15, scale=6),
                    existing_nullable=False)
    # ### end Alembic commands ###
